// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';
import { useAuth } from '@clerk/clerk-react';
import { supabase, getClient } from '@/lib/supabaseClient';
import { useCallback } from 'react';

// Export the default client for convenience
export { supabase };

// Custom hook to get a Supabase client with the current Clerk session
export const useSupabaseClient = () => {
  const { getToken } = useAuth();

  const getAuthenticatedClient = useCallback(async () => {
    try {
      const token = await getToken({ template: 'supabase' });
      
      if (!token) {
        return supabase;
      }

      return await getClient(token);
    } catch (error) {
      console.error('Error getting authenticated client:', error);
      return supabase;
    }
  }, [getToken]);

  return { getClient: getAuthenticatedClient };
};