// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbgepctuompotzsizcvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZ2VwY3R1b21wb3R6c2l6Y3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjkxNzUsImV4cCI6MjA2MTQwNTE3NX0.TAaCyLV7apkWQWvzTsTlJdYcOMWJ8bhBK4b8AKpu5kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);